id: e21b6ad33add4b799b64aea010d3f34c
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_150-The_Inquiry_of_Avalokitesvara_on_the_Seven_Qualities-v1
  language: bo
  author: ''
  volume: {}
